stages:
  - maven
  - build
  - deploy

maven_job:
  stage: maven
  tags:
    - diary-default
  only:
    - master
  script:
    - echo "This is the first maven job"

build_job:
  stage: build
  tags:
    - diary-default
  only:
    - master
  script:
    -  echo "This is the first build job"

deploy_job:
  stage: deploy
  tags:
    - diary-default
  only:
    - master
  script:
    - echo "This is the first deploy job"